spring:
  data:
    mongodb:
      uri: ${MONGODB_DATABASE_URL:mongodb+srv://pawan6186:AKNQzcWBpaYJ3aaW@cluster0.vx89hdm.mongodb.net/?retryWrites=true&w=majority}
  application:
    name: file-management

server:
  port: 8083
springdoc:
  pathsToMatch: /api/**

eureka:
  instance:
    hostname: localhost